-- 코드를 입력하세요
SELECT P.ID, P.NAME, P.HOST_ID
FROM PLACES AS P
INNER JOIN (SELECT HOST_ID
     FROM PLACES
     GROUP BY HOST_ID
     HAVING COUNT(HOST_ID) > 1) AS H
ON P.HOST_ID = H.HOST_ID
ORDER BY P.ID