-- 코드를 입력하세요
SELECT DISTINCT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS R
ON C.CAR_ID = R.CAR_ID
WHERE R.START_DATE LIKE '2022-10%' AND C.CAR_TYPE = '세단'
-- GROUP BY C.CAR_ID
ORDER BY C.CAR_ID DESC